
name: ideathon
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  provider: ^6.0.4
  flutter_iconly: ^1.0.2
  google_nav_bar: ^5.0.6
  fluentui_icons: ^1.0.0
  gap: ^2.0.0
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  firebase_storage: ^11.0.3
  cloud_firestore: ^4.0.3
  google_maps_flutter: ^2.2.1
  flutter_polyline_points: ^1.0.0
  location: ^4.4.0
  dio: ^4.0.6
  smooth_page_indicator: ^1.0.0+2
  flutter_ticket_widget: ^0.0.1
  flutter_rating_bar: ^4.0.1
  firebase_database: ^10.0.5
  google_maps_webservice: ^0.0.19
  flutter_map: ^3.0.0
  geolocator: ^9.0.2
  #geoflutterfire: any
  uuid: ^3.0.7
  #http: ^0.13.5
  alan_voice: 3.0.0
  
   


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/pngs/
    - assets/new/